
from speasy.core.hapi.client import HapiClient, HapiEndpoint
from speasy.core.hapi.provider import HapiProvider
from speasy.core.hapi.exceptions import HapiRequestError, HapiServerError, HapiNoData


AMDA_SERVER_URL = "https://amda.irap.omp.eu/service"
HAPITEST33_SERVER_URL = "https://hapi-server.org/servers/TestData3.3/"


class TestHapiClient:

    def test_build_url_capabilities(self): 
        hapi_client = HapiClient(HAPITEST33_SERVER_URL)
        result = hapi_client.get_about()
        assert result["HAPI"] == "3.3"
        assert result["status"]["code"] == 1200
        assert isinstance(result["note"], list)

    def test_build_url_info_with_dataset(self): ...
    def test_build_url_data_with_params(self): ...

    def test_get_info_returns_json(self): ...
    # mock requests.get → 200 + json valide

    def test_raises_on_http_error(self): ...
    # mock requests.get → 500

    def test_check_status_raises_hapi_request_error_on_1401(self): ...
    def test_check_status_raises_hapi_server_error_on_1500(self): ...
    def test_check_status_raises_hapi_no_data_on_1201(self): ...
    def test_check_status_does_not_raise_on_1200(self): ...

class TestHapiProvider:

    def test_capabilities_returns_dict(self): ...
    def test_catalog_returns_dict(self): ...
    def test_info_returns_dict(self): ...
    def test_about_returns_dict(self):
        hapi_provider = HapiProvider(HAPITEST33_SERVER_URL)
        result = hapi_provider.about()
        assert result["HAPI"] == "3.3"
        assert result["status"]["code"] == 1200
        assert isinstance(result["note"], list)

    def test_data_returns_speasy_variable(self): ...

    def test_data_raises_hapi_no_data_on_1201(self): ...
    def test_data_raises_hapi_request_error_on_unknown_dataset(self): ...
    def test_data_raises_hapi_request_error_on_bad_time_format(self): ...
    def test_data_raises_hapi_server_error_on_1500(self): ...
