# This file is generated from
# https://3dview.irap.omp.eu/webresources/get_frames json output

_COORDINATE_FRAMES = [
    {
        "id": 1,
        "name": "J2000",
        "desc": "Earth mean equator, dynamical equinox of J2000",
        "center": "Sun",
    },
    {
        "id": 17,
        "name": "ECLIPJ2000",
        "desc": "Ecliptic coordinates based upon the J2000 frame",
        "center": "Sun",
    },
    {
        "id": 1600010,
        "name": "HEE",
        "desc": "Heliocentric Earth Ecliptic",
        "center": "Sun",
    },
    {
        "id": 1601010,
        "name": "HEEQ",
        "desc": "Heliocentric Earth Equatorial",
        "center": "Sun",
    },
    {
        "id": 1602010,
        "name": "HCI",
        "desc": "Heliocentric Inertial",
        "center": "Sun",
    },
    {
        "id": 10010,
        "name": "IAU_SUN",
        "desc": "Body-Fixed Frame",
        "center": "Sun",
    },
    {
        "id": 1603199,
        "name": "MESO",
        "desc": "Mercury-centric Solar Orbital",
        "center": "Mercury",
    },
    {
        "id": 1600199,
        "name": "MEME",
        "desc": "EME2000 centered on Mercury",
        "center": "Mercury",
    },
    {
        "id": 1601199,
        "name": "MECLIP",
        "desc": "ECLIPJ2000 centered on Mercury",
        "center": "Mercury",
    },
    {
        "id": 1604199,
        "name": "MESE",
        "desc": "Mercury-centric Solar Ecliptic",
        "center": "Mercury",
    },
    {
        "id": 1605199,
        "name": "MESEQ",
        "desc": "Mercury-centric Solar Equatorial",
        "center": "Mercury",
    },
    {
        "id": 10011,
        "name": "IAU_MERCURY",
        "desc": "Body-Fixed Frame",
        "center": "Mercury",
    },
    {
        "id": 1600299,
        "name": "VSO",
        "desc": "Venus-centric Solar Orbital",
        "center": "Venus",
    },
    {
        "id": 1601299,
        "name": "VME",
        "desc": "Venus Mean Equator",
        "center": "Venus",
    },
    {
        "id": 10012,
        "name": "IAU_VENUS",
        "desc": "Body-Fixed Frame",
        "center": "Venus",
    },
    {
        "id": 1600399,
        "name": "GSE",
        "desc": "Geocentric Solar Ecliptic",
        "center": "Earth",
    },
    {
        "id": 1601399,
        "name": "EME",
        "desc": "Earth Mean Equator and Equinox",
        "center": "Earth",
    },
    {
        "id": 1602399,
        "name": "GSEQ",
        "desc": "Geocentric Solar Equatorial",
        "center": "Earth",
    },
    {
        "id": 1603399,
        "name": "ECLIPDATE",
        "desc": "Earth Mean Ecliptic and Equinox",
        "center": "Earth",
    },
    {
        "id": 1604399,
        "name": "MAG",
        "desc": "Geomagnetic coordinate system (definition not valid after 31/12/2014)",
        "center": "Earth",
    },
    {
        "id": 1605399,
        "name": "GSM",
        "desc": "Geocentric solar magnetospheric system  (definition not valid after 31/12/2014)",
        "center": "Earth",
    },
    {
        "id": 1606399,
        "name": "SM",
        "desc": "Solar magnetic coordinates (definition not valid after 31/12/2014)",
        "center": "Earth",
    },
    {"id": 10013, "name": "IAU_EARTH", "desc": "Body-Fixed Frame", "center": "Earth"},
        {
            "id": 1600301,
            "name": "LSE",
            "desc": "Moon-centric Solar Ecliptic",
            "center": "Moon",
        },
    {"id": 1601301, "name": "LME", "desc": "Moon Mean Equator", "center": "Moon"},
    {"id": 10020, "name": "IAU_MOON", "desc": "Body-Fixed Frame", "center": "Moon"},
    {
        "id": 1601499,
        "name": "MSO",
        "desc": "Mars-centric Solar Orbital",
        "center": "Mars",
    },
    {"id": 1600499, "name": "MME", "desc": "Mars Mean Equator", "center": "Mars"},
    {"id": 10014, "name": "IAU_MARS", "desc": "Body-Fixed Frame", "center": "Mars"},
    { "id": 1600401, "name": "PSE", "desc": "Phobos-centric Solar Ecliptic", "center": "Phobos", },
    {"id": 1601401, "name": "PME", "desc": "Phobos Mean Equator", "center": "Phobos"},
    {
        "id": 1600402,
        "name": "DSE",
        "desc": "Deimos-centric Solar Ecliptic",
        "center": "Deimos",
    },
    {"id": 1601402, "name": "DME", "desc": "Deimos Mean Equator", "center": "Deimos"},
    {
        "id": 1603599,
        "name": "JSO",
        "desc": "Jovian Solar Orbital Coordinates",
        "center": "Jupiter",
    },
    {
        "id": 1600599,
        "name": "JEME",
        "desc": "EME2000 centered on Jupiter",
        "center": "Jupiter",
    },
    {
        "id": 1601599,
        "name": "JECLIP",
        "desc": "ECLIPJ2000 centered on Jupiter",
        "center": "Jupiter",
    },
    {
        "id": 1602599,
        "name": "JSM",
        "desc": "Jovian Solar Magnetospheric",
        "center": "Jupiter",
    },
    {"id": 1604599, "name": "SYSTEM_3", "desc": "System 3", "center": "Jupiter"},
    {
        "id": 10015,
        "name": "IAU_JUPITER",
        "desc": "Body-Fixed Frame using IAU 2009 constants ",
        "center": "Jupiter",
    },
    {"id": 1600501, "name": "IPHIO", "desc": "Io phio", "center": "Io"},
    {"id": 1600502, "name": "EPHIO", "desc": "Europa phio", "center": "Europa"},
    {"id": 1600503, "name": "GPHIO", "desc": "Ganymede phio", "center": "Ganymede"},
    {"id": 1600504, "name": "CPHIO", "desc": "Callisto phio", "center": "Callisto"},
    {
        "id": 1603699,
        "name": "KSO",
        "desc": "Kronocentric Solar Orbital Coordinates",
        "center": "Saturn",
    },
    {
        "id": 1600699,
        "name": "KEME",
        "desc": "EME2000 centered on Saturn",
        "center": "Saturn",
    },
    {
        "id": 1601699,
        "name": "KECLIP",
        "desc": "ECLIPJ2000 centered on Saturn",
        "center": "Saturn",
    },
    {
        "id": 1602699,
        "name": "KSM",
        "desc": "Kronocentric Solar Magnetospheric",
        "center": "Saturn",
    },
    {"id": 10016, "name": "IAU_SATURN", "desc": "Body-Fixed Frame", "center": "Saturn"},
    {
        "id": 1600601,
        "name": "MIIS",
        "desc": "Mimas Inter-action coordinate System",
        "center": "Mimas",
    },
    {
        "id": 1600602,
        "name": "ENIS",
        "desc": "Enceladus Inter-action coordinate System",
        "center": "Enceladus",
    },
    {
        "id": 1600603,
        "name": "TEIS",
        "desc": "Tethys Inter-action coordinate System",
        "center": "Tethys",
    },
    {
        "id": 1600604,
        "name": "DIIS",
        "desc": "Dione Inter-action coordinate System",
        "center": "Dione",
    },
    {
        "id": 1600605,
        "name": "RHIS",
        "desc": "Rhea Inter-action coordinate System",
        "center": "Rhea",
    },
    {
        "id": 1600606,
        "name": "TIIS",
        "desc": "TItan Inter-action coordinate System",
        "center": "Titan",
    },
    {
        "id": 1600799,
        "name": "UEME",
        "desc": "EME2000 centered on Uranus",
        "center": "Uranus",
    },
    {
        "id": 1601799,
        "name": "UECLIP",
        "desc": "ECLIPJ2000 centered on Uranus",
        "center": "Uranus",
    },
    {
        "id": 1603799,
        "name": "USO",
        "desc": "Uranus-centric Solar Orbital Coordinates",
        "center": "Uranus",
    },
    {
        "id": 10017,
        "name": "IAU_URANUS",
        "desc": "Body-Fixed Frame",
        "center": "Uranus",
    },
    {
        "id": 1600899,
        "name": "NEME",
        "desc": "EME2000 centered on Neptune",
        "center": "Neptune",
    },
    {
        "id": 1601899,
        "name": "NECLIP",
        "desc": "ECLIPJ2000 centered on Neptune",
        "center": "Neptune",
    },
    {
        "id": 1603899,
        "name": "NSO",
        "desc": "Neptune-centric Solar Orbital Coordinates",
        "center": "Neptune",
    },
    {
        "id": 10018,
        "name": "IAU_NEPTUNE",
        "desc": "Body-Fixed Frame",
        "center": "Neptune",
    },
    {
        "id": 1600999,
        "name": "PEME",
        "desc": "EME2000 centered on Pluto",
        "center": "Pluto",
    },
    {
        "id": 1601999,
        "name": "PECLIP",
        "desc": "ECLIPJ2000 centered on Pluto",
        "center": "Pluto",
    },
    {
        "id": 1603999,
        "name": "PSO",
        "desc": "Pluto-centric Solar Orbital Coordinates",
        "center": "Pluto",
    },
    {"id": 10019, "name": "IAU_PLUTO", "desc": "Body-Fixed Frame", "center": "Pluto"},
    {
        "id": 1601000012,
        "name": "67PCG_EME",
        "desc": "EME2000 centered on comet churyumov gerasimenko",
        "center": "Churyumov-Gerasimenko",
    },
    {
        "id": 1611000012,
        "name": "67PCG_CSO",
        "desc": "Comet solar oriented  centered on comet churyumov gerasimenko",
        "center": "Churyumov-Gerasimenko",
    },
    {
        "id": 1602000021,
        "name": "LUTETIA_EME",
        "desc": "EME2000 centered on asteroid LUTETIA",
        "center": "Lutetia",
    },
    {
        "id": 1612000021,
        "name": "LUTETIA_CSO",
        "desc": "Comet solar oriented  centered on asteroid LUTETIA",
        "center": "Lutetia",
    },
    {
        "id": 1602002867,
        "name": "STEINS_EME",
        "desc": "EME2000 centered on asteroid STEINS",
        "center": "Steins",
    },
    {
        "id": 1612002867,
        "name": "STEINS_CSO",
        "desc": "Comet solar oriented  centered on asteroid STEINS",
        "center": "Steins",
    },
    {
        "id": 1601000036,
        "name": "HALLEY_EME",
        "desc": "EME2000 centered on asteroid HALLEY",
        "center": "Halley",
    },
    {
        "id": 1611000036,
        "name": "HALLEY_CSO",
        "desc": "Comet solar oriented  centered on asteroid HALLEY",
        "center": "Halley",
    },
    {
        "id": 1601000034,
        "name": "GRIGGSKELL_EME",
        "desc": "EME2000 centered on asteroid GRIGG-SKJELLERUP",
        "center": "Grigg-Skjellerup",
    },
    {
        "id": 1611000034,
        "name": "GRIGGSKELL_CSO",
        "desc": "Comet solar oriented  centered on asteroid GRIGG-SKJELLERUP",
        "center": "Grigg-Skjellerup",
    },
    {
        "id": 10113,
        "name": "IAU_DIDYMOS",
        "desc": "Body-Fixed Frame",
        "center": "Didymos",
    },
    {
        "id": 200658031,
        "name": "DIDYMOS_EME",
        "desc": "EME2000 centered on asteroid DIDYMOS",
        "center": "Didymos",
    },
    {
        "id": 200658032,
        "name": "DIDYMOS_CSO",
        "desc": "Comet solar oriented centered on asteroid DIDYMOS",
        "center": "Didymos",
    },
]
